### ISSUE TITLE
The kinch scores seem to not be calculated correctly

### ISSUE THREAD

**Issue by DSTGU** [AlphaSheep/Comp-Kinch#17]
For example: 

In Energy Cube Koło 2023 
https://live.worldcubeassociation.org/competitions/2360/rounds/33248
https://comp-kinch.sylvermyst.com/#/competition/EnergyCubeKolo2023
Kajetan Opach has gotten 6.61 average in the finals of 3x3. Winner of 3x3 has gotten 5.22 average. If we plug these values into Kinch equation (5.22/6.61*100) we get 79.0 after rounding. Your site says it s 82.5. Results from any other round of 3x3 dont match this statistic either. (94.9 R2, 81.4 R1) I even tried crossreferencing the rounds but that also doesnt give result present on the site. Similar inaccuracies are in most of the results. This should either be fixed or there should be an explanation available for why results on the site are the way they are

**Comment by AlphaSheep** [comment]
Hi @DSTGU. The KinchRank calculation ignores rounds. The best 3x3 average at the competition was 5.22. Kajetan Opach's best 3x3 average at the competition was 6.33. Their Kinch score for 3x3 is therefore (5.22/6.33 * 100) which is 82.5 after rounding.

I had to make some choices about how to treat rounds, so I opted for thinking about it as "What would the global KinchRanks look like if this competition was the only one in existence". There are other ways of considering it and other sites that calculate competition KinchRanks may choose a different option, but this is the way that I feel is more consistent with the definitions in use for world, continent, and country KinchRanks.

You can see the full methodology [here](https://comp-kinch.sylvermyst.com/#/about).

Let me know if you have any more questions!

**Comment by DSTGU** [comment]
Energy Cube has financial rewards for Kinch results and their Kinch is calculated differently: 

https://www.worldcubeassociation.org/competitions/EnergyCubeCiechanow2023#29486-allrounder-champion

This sounds like another of three ways to do it: Last round score, last round score with mercy rule (cant get worse score than n+1 for previous round), best score

I think I would've opted for a different solution, but this one seems good. Considering that there is no standard for how kinch should be calculated in a competition with multiple rounds this can be closed. I ll go talk with EC guys now on how and why they are doing things. Thank you for explaining
